config/routes.rb
Minewallet::Application.routes.draw do

  resources :accounts

  resources :rules

  resources :transactions

  devise_for :users

  authenticated :user do
    root :to => "transactions#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :accounts do
    resources :transactions
    resources :rules
  end

end

app/views/shared/_aside.html.erb
    <div class="well" style="padding: 8px 0;">
      <ul class="nav nav-list">
        <li class="nav-header">Кошельки</li>
          <% current_user.accounts.each do |account| %>
            <li>
              <%= link_to account_transactions_path(account) do%>
                <%= account.title%> (<%= account.balance %> <%= account.currency %>)
              <% end %>
            </li>
          <% end %>
        <li class="nav-header">Быстрые транзакции</li>
        <% current_user.rules.each do |rule| %>
          <li>
          <%#link_to( "#apply-confirm", :class=>"apply-confirm") do %>
            <%= link_to rule.title, rule_path(rule)%>
          <% #end %>
          </li>
          <% end %>
      </ul>
    </div>

app/views/shared/_error.html.erb
  <% if object.errors.any? %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">&#215;</a>
        <ul>
          <% object.errors.full_messages.each do |msg| %>
            <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
          <% end %>
        </ul>
    </div>
  <% end %>

app/views/shared/_transactions_table.html.erb
  <table class="table table-striped">
    <% @transactions.each do |transaction| %>
      <tr>
        <td>
          <%= kind_title(transaction) %>
          <span class="label warning"><%= transaction.account.title%></span>
          <span class="label info"><%= transaction.tags %></span>
          <br/><%= transaction.created_at %>
        </td>
        <td>
          <h3><%= transaction.amount %> <%= transaction.account.currency %></h3>
          <small><%= transaction.description %></small>
        </td>
        <td>
          <div class="btn-group pull-right">
            <%= edit_transaction_link(transaction) %>
            <%= delete_transaction_link(transaction) %>
          </div>
        </td>
      </tr>
  <% end %>
  </table>