config/routes.rb
Minewallet::Application.routes.draw do

  resources :accounts

  resources :rules

  resources :transactions

  devise_for :users

  authenticated :user do
    root :to => "transactions#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :accounts do
    resources :transactions
    resources :rules
  end

end

app/models/rule.rb
class Rule < Storage
  belongs_to :account

  validates :title, :length => { :minimum => 3, :maximum=>35 }, :uniqueness => true
  validates :account_id, :presence => true
  validates_inclusion_of :kind, :in => [0,1]
  validates :tags, :length => { :minimum => 2, :maximum=>25 }, :unless => "tags.blank?"
  validates_numericality_of :amount, :greater_than => 0
  validates :description, :length => {  :maximum=>256 }
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]
  before_action :isset_account
  # GET /rules
  # GET /rules.json
  def index
    @rules = current_user.rules
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
    @transaction = @rule
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to rules_path, notice: 'Rule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rule }
      else
        format.html { render action: 'new' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to rules_path, notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params[:rule].permit(:title, :account_id, :kind, :tags, :amount, :description)
    end

    def isset_account
      redirect_to root_path if current_user.accounts.empty?
    end


end

app/helpers/rules_helper.rb
module RulesHelper
  def kind_title(rule)
    if rule.kind.to_i == 1
      content_tag(:span, t("transactions.income"), :class =>"label success")
    else
      content_tag(:span, t("transactions.expense"), :class=>"label important")
    end
  end
end

app/views/rules/_apply.html.erb
<%= form_for @rule, :url =>transactions_path, :as=> :transaction, :method => :post do |f| %>
  <%= render "shared/error", object: @rule %>

  <div id="field" class="control-group">
    <%= f.label :account_id, :class=>"control-label" %>
    <div class="controls">
      <%= f.select(:account_id, options_from_collection_for_select(current_user.accounts.all, :id, :title, :selected => @rule.account_id) )%>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :kind, :class=>"control-label"%>
    <div class="controls">
      <%= f.select(:kind, options_for_select([['Расход', 0], ['Доход', 1]], @rule.kind))%>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :tags, :class=>"control-label"%>
    <div class="controls">
      <%= f.text_field :tags, :class=>"input-xlarge"%>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :amount, :class=>"control-label"%>
    <div class="controls">
      <%= f.text_field :amount, :class=>"input-xlarge"%>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :description, :class=>"control-label" %>
    <div class="controls">
      <%= f.text_area :description, :class=>"span6" %>
      <span class="help-inline"></span>
    </div>
  </div>
  <div id="field" class="control-group">
    <div class="controls">
      <div class="actions">
        <%= submit_tag  'Save', :type => :submit, :class => 'btn btn-primary' %>
        <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger"%>
      </div>
    </div>
  </div>
<% end %>

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <%= render "shared/error", object: @rule %>
  <div id="field" class="control-group">
    <%= f.label :title, :class=>"control-label" %>
    <div class="controls">
      <%= f.text_field :title, :class=>"input-xlarge" %>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :account_id, :class=>"control-label" %>
    <div class="controls">
      <%= f.select(:account_id, options_from_collection_for_select(current_user.accounts.all, :id, :title, :selected => @rule.account_id) )%>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :kind, :class=>"control-label"%>
    <div class="controls">
      <%= f.select(:kind, options_for_select([['Расход', 0], ['Доход', 1]], @rule.kind))%>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :tags, :class=>"control-label"%>
    <div class="controls">
      <%= f.text_field :tags, :class=>"input-xlarge"%>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :amount, :class=>"control-label"%>
    <div class="controls">
      <%= f.text_field :amount, :class=>"input-xlarge"%>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :description, :class=>"control-label" %>
    <div class="controls">
      <%= f.text_area :description, :class=>"span6" %>
      <span class="help-inline"></span>
    </div>
  </div>
  <div id="field" class="control-group">
    <div class="controls">
      <div class="actions">
        <%= submit_tag  'Save', :type => :submit, :class => 'btn btn-primary' %>
        <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger"%>
      </div>
    </div>
  </div>
<% end %>

app/views/rules/edit.html.erb
<h1><%=t '.title' %></h1>

<%= render 'form' %>

app/views/rules/index.html.erb
<table class="table table-striped">
    <% @rules.each do |rule| %>
      <tr>
        <td>
          <%= kind_title(rule) %>
          <span class="label warning"><%= rule.account.title%></span>
          <span class="label info"><%= rule.tags %></span>
        </td>
        <td>
          <h3><%= rule.title %></h3>
          <h3><%= rule.amount %> <%# transaction.account.currency %></h3>
          <small><%= rule.description %></small>
        </td>
        <td>
      <div class="btn-group pull-right">
          <%= link_to rule, :class=>"btn btn-mini btn-success" do %>
            <i class="icon-ok icon-white"></i> Применить правило
          <% end %>

          <%= link_to edit_rule_path(rule), :class=>"btn btn-mini btn-success" do %>
            <i class="icon-edit icon-white"></i> Редатрировать
          <% end %>

          <%= link_to rule, method: :delete, data: { confirm: 'Are you sure?', :class=>"confirm" }, :class=>"btn btn-mini btn-danger delete" do %>
            <i class="icon-trash icon-white"></i> Удалить
          <%end%>
      </div>
        </td>
      </tr>
  <% end %>
  </table>

<%= link_to(new_rule_path, :class=>"btn btn-large btn-success") do %>
  <i class="icon-plus icon-white"></i>Добавить правило
<% end %>

app/views/rules/new.html.erb
<h1><%=t '.title' %></h1>

<%= render 'form' %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>
<h3>Применить правило "<%= @rule.title %>"</h3>
<%= render :partial=>"apply"%>