config/routes.rb
Minewallet::Application.routes.draw do

  resources :accounts

  resources :rules

  resources :transactions

  devise_for :users

  authenticated :user do
    root :to => "transactions#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :accounts do
    resources :transactions
    resources :rules
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :transactions, :dependent => :destroy
  has_many :rules, :dependent => :destroy

  validates :title, :length => { :minimum => 3, :maximum=>15 }, :uniqueness => true
  validates_inclusion_of :currency, :in => ["AED",   "ARS",    "ATS",    "AUD",    "BEF",    "BHD",    "BOB",    "BRL",    "CAD",    "CHF",    "CLP",    "CNY",   "CZK",    "DEM",    "DKK",    "EGP",    "ESP",    "EUR",    "FIM",    "FJD",    "FRF",    "GBP",    "GRD",    "HKD",    "IDR",    "IEP",    "ILS",    "INR",    "ITL",    "JMD",    "JPY",    "KRW",    "KWD",    "LKR",    "MXN",    "MYR",    "NLG",    "NOK",    "NPR",    "NZD",    "PAB",    "PGK",    "PHP",    "PKR",    "PTE",    "RUR",    "SAR",    "SBD",    "SEK",    "SGD",    "THB",    "TOP",    "TRL",    "TWD",    "USD", "VUV", "ZAR"]
  validates_numericality_of :balance, :greater_than => 0

  def self.currency_hash
    {
    "AED" => " дирхам - ОАЭ",
    "ARS" => " песо - Аргентина ",
    "ATS" => " шиллинг - Австрия ",
    "AUD" => " доллар - Австралия ",
    "BEF" => " франк - Бельгия ",
    "BHD" => " динар - Бахрейн ",
    "BOB" => " боливьяно - Боливия",
    "BRL" => " реал - Бразилия ",
    "CAD" => " доллар - Канада ",
    "CHF" => " франк - Швейцария",
    "CLP" => " песо -Чили ",
    "CNY" => " юань - Китай",
    "CZK" => " крона - Чехия",
    "DEM" => " немецкая марка - Германия ",
    "DKK" => " крона - Дания ",
    "EGP" => " фунт - Египет ",
    "ESP" => " песета - Испания",
    "EUR" => " евро ",
    "FIM" => " марка - Финляндия ",
    "FJD" => " доллар - Фиджи ",
    "FRF" => " франк - Франция ",
    "GBP" => " фунт стерлинга ",
    "GRD" => " драхма - Греция ",
    "HKD" => " доллар - Гонконг ",
    "IDR" => " рупия - Индонезия ",
    "IEP" => " фунт - Ирландия ",
    "ILS" => " шекель - Израиль ",
    "INR" => " рупия - Индия ",
    "ITL" => " лира - Италия ",
    "JMD" => " доллар - Ямайка",
    "JPY" => " иена - Япония ",
    "KRW" => " вон - Южная Корея",
    "KWD" => " динар - Кувейт ",
    "LKR" => " рупия - Шри-Ланка",
    "MXN" => " песо - Мексика ",
    "MYR" => " ринггит - Малайзия",
    "NLG" => " гульден - Нидерланды",
    "NOK" => " крона - Норвегия ",
    "NPR" => " рупия - Непал ",
    "NZD" => " доллар - Новая Зеландия ",
    "PAB" => " бальбоа - Панама ",
    "PGK" => " кина  - Папуа Новая Гвинея",
    "PHP" => " песо - Филиппины ",
    "PKR" => " рупия - Пакистан ",
    "PTE" => " эскудо - Португалия",
    "RUR" => " рубль - Россия ",
    "SAR" => " риял - Сайдовская Аравия ",
    "SBD" => " доллар  Соломоновы острова",
    "SEK" => " крона - Швеция ",
    "SGD" => " доллар - Сингапур",
    "THB" => " бат - Таиланд ",
    "TOP" => " паанга - Тоонго",
    "TRL" => " лира - Турция ",
    "TWD" => " доллар - Новый Тайвань",
    "USD" => " доллар - США ",
    "VUV" => " вату - Вануату",
    "ZAR" => " ранд - ЮАР"}
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :isset_account, :except => [:new, :create]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = current_user.accounts.all
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = current_user.accounts.new(account_params)

    respond_to do |format|
      if @account.save
        format.html {
          redirect_to transactions_path, notice: 'Account was successfully created.' if current_user.accounts.count > 1
          redirect_to transactions_path, notice: 'Поздравляем с созданием первого кошелька! Теперь все готово к использованию сервиса!' if current_user.accounts.count == 1 && current_user.transactions.empty?
        }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
        format.html { redirect_to accounts_url }
        format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = current_user.accounts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :title, :currency, :balance)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def new_account_link
    link_to(new_account_path,  :class=>"btn btn-large btn-success") do
        content_tag(:i, "", :class => "") + t("accounts.new.title")
    end
  end

  def delete_account_link(account)
    link_to(account, method: :delete, data: { confirm: 'Are you sure?', :class=>"confirm" }, :class=>"btn btn-mini btn-danger delete") do
        content_tag(:i, "", :class => "icon-trash icon-white") + t("accounts.destroy")
    end
  end

  def edit_account_link(account)
      link_to(edit_account_path(account), :class=>"btn btn-mini btn-success") do
        content_tag(:i, "", :class => "icon-edit icon-white") + t("account.edit")
      end
  end
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <fieldset>
    <%= render "shared/error", object: @account %>
  <div id="field" class="control-group">
    <%= f.label :title, :class=>"control-label" %>
    <div class="controls">
      <%= f.text_field :title, :class=>"input-xlarge" %>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :currency, :class=>"control-label" %>
    <div class="controls">
      <%= f.select(:currency, options_for_select(Account.currency_hash.map { |key, value| [key + value, key] }, "RUR"))%>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <%= f.label :balance, :class=>"control-label" %>
    <div class="controls">
      <%= f.text_field :balance, :class=>"input-xlarge" %>
      <span class="help-inline"></span>
    </div>
  </div>

  <div id="field" class="control-group">
    <div class="controls">
      <div class="actions">
        <%= f.button  :type => :submit, :class => 'btn btn-primary' %>
        <%= f.button t("reset"), :type => :reset, :class => "btn btn-danger"%>
        <%= link_to t("cancel"),accounts_path , :class => "btn btn-danger"%>
      </div>
    </div>
  </div>
  </fieldset>

<% end %>

app/views/accounts/edit.html.erb
<h1><%=t '.title' %></h1>

<%= render 'form' %>

app/views/accounts/index.html.erb
<% if @accounts.size >0 %>
<table class="table table-stripped">
  <tr>
    <th>Название</th>
    <th>Валюта</th>
    <th>Баланс</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><h3><%= account.title %></h3></td>
    <td><%= account.currency %></td>
    <td><%= account.balance %> <%= account.currency %></td>
    <td>
      <div class="btn-group pull-right">
        <%= link_to(new_account_transaction_path(account), :class=>"btn btn-mini btn-success") do %>
          <i class="icon-plus icon-white"></i> транзакцию
        <% end %>
        <%= link_to(new_account_transaction_path(account), :class=>"btn btn-mini btn-success") do %>
          <i class="icon-plus icon-white"></i> правило
        <% end %>

        <%= edit_account_link(account) %>
        <%= delete_account_link(account) %>
      </div>
      </td>
  </tr>
<% end %>
</table>

<br />
<% else %>
  <h1> Нет доступных кошельков! Создайте!</h1>
  <% end %>
<%= new_account_link %>

app/views/accounts/new.html.erb
<h1><%=t '.title' %></h1>

<%= render 'form' %>